spring.application.name=flashcardBackend

# Database URL
spring.datasource.url=jdbc:postgresql://userver.local:5011/password?createDatabaseIfNotExist=true

# Database username and password
spring.datasource.username=rootatkali
spring.datasource.password=rootwizz

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
